"""
Behave test steps for RFC update scenarios (User Story 2)
"""

import os
import json
import subprocess
from pathlib import Path
from datetime import datetime
from behave import given, when
from behave.runner import Context

# Import assertion steps
from update_assertions import *  # noqa: F401, F403


# ============================================================================
# Given Steps - Setup Test Conditions for Update Scenarios
# ============================================================================

@given('an existing RFC document has been generated')
def step_existing_rfc_generated(context: Context):
    """Set up an existing RFC document for update tests with matching source code"""

    # ===== 1. CREATE SOURCE CODE FIRST =====
    # This is the code that the RFC will document
    src_dir = os.path.join(str(context.test_repo), 'src')
    os.makedirs(src_dir, exist_ok=True)

    calculator_py = os.path.join(src_dir, 'calculator.py')
    with open(calculator_py, 'w') as f:
        f.write('''"""
Calculator module for basic arithmetic operations
"""

class Calculator:
    """
    A simple calculator class

    Attributes:
        history: List of calculation operations performed
    """

    def __init__(self):
        """Initialize calculator with empty history"""
        self.history = []

    def add(self, a: float, b: float) -> float:
        """
        Add two numbers

        Args:
            a: First operand
            b: Second operand

        Returns:
            Sum of a and b
        """
        result = a + b
        self.history.append(('add', a, b, result))
        return result

    def subtract(self, a: float, b: float) -> float:
        """
        Subtract b from a

        Args:
            a: Minuend
            b: Subtrahend

        Returns:
            Difference of a minus b
        """
        result = a - b
        self.history.append(('subtract', a, b, result))
        return result
''')

    context.sample_code_file = calculator_py

    # ===== 2. NOW GENERATE RFC USING REAL /rfc-generate COMMAND =====
    # Import command runner
    import sys
    support_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'support')
    if support_dir not in sys.path:
        sys.path.insert(0, support_dir)

    from command_runner import run_slash_command

    # Run REAL /rfc-generate command to create RFC from source code
    result = run_slash_command(
        str(context.test_repo),
        '/rfc-generate src/ --output draft-calculator-00.md',
        serena_available=getattr(context, 'serena_mcp_available', True)
    )

    # Verify RFC generation succeeded
    assert result.exit_code == 0, f"RFC generation failed with exit code {result.exit_code}. Errors: {result.errors}"
    assert result.files_created, f"No files were created by /rfc-generate. Output: {result.output}"

    # Find the generated RFC file
    rfc_files = [f for f in result.files_created if f.endswith('.md') and 'draft-' in f]
    assert len(rfc_files) > 0, f"No RFC file generated. Files created: {result.files_created}"

    # Store RFC path for use in subsequent steps
    context.existing_rfc_path = rfc_files[0]

    # Verify RFC file actually exists on disk
    assert os.path.exists(context.existing_rfc_path), f"RFC file {context.existing_rfc_path} not found on disk"


@given('an existing RFC document')
def step_existing_rfc_generic(context: Context):
    """Set up an existing RFC document (wrapper for background step)"""
    step_existing_rfc_generated(context)


@given('an rfc-map.json file exists with code mappings')
def step_rfc_map_exists(context: Context):
    """
    Verify rfc-map.json exists (should be created by /rfc-generate in previous step).

    This step is now validation-only. The rfc-map.json file should have been
    automatically generated by the /rfc-generate command in the
    'an existing RFC document has been generated' step.
    """
    # Determine expected rfc-map.json path
    context.rfc_map_path = os.path.join(str(context.test_repo), 'docs', 'rfc-map.json')

    # Verify file was created by /rfc-generate
    assert os.path.exists(context.rfc_map_path), (
        f"rfc-map.json not found at {context.rfc_map_path}. "
        "It should have been generated by /rfc-generate command in previous step."
    )

    # Verify it contains valid JSON
    try:
        with open(context.rfc_map_path, 'r') as f:
            rfc_map = json.load(f)
    except json.JSONDecodeError as e:
        raise AssertionError(f"rfc-map.json contains invalid JSON: {e}")

    # Verify basic structure
    assert 'version' in rfc_map, "rfc-map.json missing 'version' field"
    assert 'mappings' in rfc_map, "rfc-map.json missing 'mappings' field"
    assert isinstance(rfc_map['mappings'], list), "rfc-map.json 'mappings' must be a list"

    # Verify it contains at least some mappings (not empty)
    assert len(rfc_map['mappings']) > 0, (
        "rfc-map.json contains no mappings. /rfc-generate should have created code-to-RFC mappings."
    )


@given('an existing RFC document at "{rfc_path}"')
def step_existing_rfc_at_path(context: Context, rfc_path: str):
    """Verify RFC exists at specified path"""
    full_path = os.path.join(str(context.test_repo), rfc_path)
    if not os.path.exists(full_path):
        # Create it if it doesn't exist (for test setup)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        context.existing_rfc_path = full_path
        step_existing_rfc_generated(context)


@given('an rfc-map.json mapping "{symbol}" to section "{section}"')
def step_rfc_map_mapping_symbol(context: Context, symbol: str, section: str):
    """Verify rfc-map.json contains specific mapping"""
    # This is set up by step_rfc_map_exists
    assert os.path.exists(context.rfc_map_path), "rfc-map.json does not exist"


@given('an existing RFC with a "{marker}" block')
def step_rfc_with_preserve_block(context: Context, marker: str):
    """Add a @preserve block to the existing RFC"""
    with open(context.existing_rfc_path, 'r') as f:
        content = f.read()

    # Replace Security Considerations section with preserve block
    updated_content = content.replace(
        "**[REVIEW REQUIRED]** Security analysis requires human expertise",
        f'''{marker}

**[MANUAL EDIT]** The Calculator service processes user-provided numeric inputs.
Implementations MUST validate input types and ranges to prevent:

1. **Integer Overflow**: Reject values exceeding platform limits
2. **Division by Zero**: The divide() method includes explicit checks (§3.3)
3. **Type Confusion**: All inputs MUST be validated as numeric types

These security requirements were reviewed with the security team on 2025-10-10.

@preserve-end'''
    )

    with open(context.existing_rfc_path, 'w') as f:
        f.write(updated_content)

    context.preserve_block_id = marker.split('id:')[-1] if 'id:' in marker else None


@given('the preserve block is in the "{section}" section')
def step_preserve_block_in_section(context: Context, section: str):
    """Verify preserve block is in specified section"""
    context.preserve_block_section = section


@given('no code changes have been made since last RFC update')
def step_no_code_changes(context: Context):
    """Simulate no code changes (clean git state)"""
    context.code_changed = False


@given('an existing RFC with nested "{marker}" markers')
def step_rfc_with_nested_markers(context: Context, marker: str):
    """Create RFC with nested (invalid) preserve markers"""
    with open(context.existing_rfc_path, 'r') as f:
        content = f.read()

    # Add nested preserve blocks (invalid)
    updated_content = content.replace(
        "**[REVIEW REQUIRED]** Security analysis requires human expertise",
        '''@preserve-start id:block1
Content A
  @preserve-start id:block2
  Content B
  @preserve-end
Content C
@preserve-end'''
    )

    with open(context.existing_rfc_path, 'w') as f:
        f.write(updated_content)


@given('the preserve blocks overlap at lines {start1:d}-{end1:d} and {start2:d}-{end2:d}')
def step_preserve_blocks_overlap(context: Context, start1: int, end1: int, start2: int, end2: int):
    """Document overlapping preserve block line ranges"""
    context.overlap_range1 = (start1, end1)
    context.overlap_range2 = (start2, end2)


@given('an existing RFC with a preserve block in section "{section}"')
def step_preserve_block_in_specific_section(context: Context, section: str):
    """Add preserve block to a specific RFC section"""
    step_rfc_with_preserve_block(context, f"@preserve-start id:custom-notes")
    context.preserve_block_section = section


@given('an existing RFC with {num:d} sections')
def step_rfc_with_n_sections(context: Context, num: int):
    """Verify RFC has specified number of sections"""
    context.expected_section_count = num


@given('an existing rfc-map.json with {num:d} mappings')
def step_rfc_map_with_n_mappings(context: Context, num: int):
    """Verify rfc-map.json has specified number of mappings"""
    with open(context.rfc_map_path, 'r') as f:
        data = json.load(f)
    assert len(data['mappings']) == num, f"Expected {num} mappings, found {len(data['mappings'])}"


@given('mapping "{symbol}" has timestamp "{timestamp}"')
def step_mapping_has_timestamp(context: Context, symbol: str, timestamp: str):
    """Verify mapping has specific timestamp"""
    with open(context.rfc_map_path, 'r') as f:
        data = json.load(f)

    for mapping in data['mappings']:
        if mapping['code']['symbol'] == symbol:
            assert mapping['last_synced'] == timestamp
            break


@given('no existing RFC document at "{rfc_path}"')
def step_no_rfc_at_path(context: Context, rfc_path: str):
    """Ensure RFC does not exist at path"""
    full_path = os.path.join(str(context.test_repo), rfc_path)
    if os.path.exists(full_path):
        os.remove(full_path)
    context.existing_rfc_path = full_path


@given('the "{file_path}" file is missing')
def step_file_is_missing(context: Context, file_path: str):
    """Remove a file to simulate missing dependency"""
    full_path = os.path.join(str(context.test_repo), file_path)
    if os.path.exists(full_path):
        os.remove(full_path)


@given('an existing RFC with preserve block "{block_id}" in lines {start:d}-{end:d}')
def step_preserve_block_at_lines(context: Context, block_id: str, start: int, end: int):
    """Create preserve block at specific line range"""
    context.preserve_block_lines = (start, end)
    context.preserve_block_id = block_id


@given('the preserve block contains manual implementation notes')
def step_preserve_block_has_manual_notes(context: Context):
    """Mark that preserve block contains manual content"""
    context.preserve_block_has_manual_content = True


@given('an existing RFC with internal cross-references')
def step_rfc_with_cross_references(context: Context):
    """Add internal cross-references to RFC"""
    # Already present in default RFC via {{terminology}} anchors
    context.has_cross_references = True


@given('section "{section_id}" references section "{ref_section}" with anchor "{anchor}"')
def step_section_references_other(context: Context, section_id: str, ref_section: str, anchor: str):
    """Document cross-reference between sections"""
    context.cross_reference = {
        'from': section_id,
        'to': ref_section,
        'anchor': anchor
    }


@given('an existing RFC with "{marker_type}" markers')
def step_rfc_with_code_ref_markers(context: Context, marker_type: str):
    """Verify RFC has CODE_REF markers"""
    # Already present in default RFC
    context.has_code_ref_markers = True


@given('an existing RFC with frontmatter containing "{field}: {value}"')
def step_rfc_with_frontmatter_field(context: Context, field: str, value: str):
    """Verify RFC frontmatter contains field"""
    with open(context.existing_rfc_path, 'r') as f:
        content = f.read()
    assert f'{field}: {value}' in content or f'{field}: "{value}"' in content


# ============================================================================
# When Steps - Execute Update Commands
# ============================================================================

@when('I modify "{file_path}" method "{method_name}" signature')
def step_modify_method_signature(context: Context, file_path: str, method_name: str):
    """Simulate modifying a method signature"""
    full_path = os.path.join(str(context.test_repo), file_path)

    # Read existing file
    with open(full_path, 'r') as f:
        content = f.read()

    # Simulate signature change: add optional parameter 'c'
    if 'def add(self, a: float, b: float)' in content:
        modified_content = content.replace(
            'def add(self, a: float, b: float) -> float:',
            'def add(self, a: float, b: float, c: float = 0.0) -> float:'
        )
        modified_content = modified_content.replace(
            '"""Add two numbers"""',
            '"""Add two or three numbers"""'
        )
        modified_content = modified_content.replace(
            'return a + b',
            'return a + b + c'
        )

        with open(full_path, 'w') as f:
            f.write(modified_content)

        context.code_changed = True
        context.modified_file = file_path
        context.modified_method = method_name


@when('I modify "{file_path}" method "{method_name}"')
def step_modify_method(context: Context, file_path: str, method_name: str):
    """Simulate modifying a method (generic)"""
    step_modify_method_signature(context, file_path, method_name)


@given('I modify "{file_path}" by adding a new parameter to "{method_name}"')
def step_modify_by_adding_parameter(context: Context, file_path: str, method_name: str):
    """Simulate adding a parameter to a method"""
    step_modify_method_signature(context, file_path, method_name)


@given('I modify "{file_path}" method "{method_name}"')
def step_modify_method_given(context: Context, file_path: str, method_name: str):
    """Simulate modifying a method (given variant)"""
    step_modify_method_signature(context, file_path, method_name)


@given('I modify only "{file_path}" method "{method_name}" (section {section})')
def step_modify_method_with_section_tracking(context: Context, file_path: str, method_name: str, section: str):
    """Simulate modifying a method with section tracking"""
    step_modify_method_signature(context, file_path, method_name)
    context.affected_section = section
    context.modified_section_filter = [section]


@given('I modify "{file_path}" method "{method_name}" (section {section})')
def step_modify_method_with_section(context: Context, file_path: str, method_name: str, section: str):
    """Simulate modifying a method with section notation"""
    step_modify_method_signature(context, file_path, method_name)
    context.affected_section = section


@when('I run "{command}"')
def step_run_update_command(context: Context, command: str):
    """Execute /rfc-update or /rfc-generate command using real implementation"""
    import sys
    from pathlib import Path

    # Add tests/support to sys.path for imports
    support_dir = Path(__file__).parent.parent / 'support'
    if str(support_dir) not in sys.path:
        sys.path.insert(0, str(support_dir))

    from command_runner import run_slash_command

    context.command = command

    # Check if Serena MCP availability was set in context
    serena_available = getattr(context, 'serena_mcp_available', True)

    # Execute command using real implementation
    result = run_slash_command(str(context.test_repo), command, serena_available=serena_available)

    # Store results in context
    context.command_exit_code = result.exit_code
    context.command_output = result.output + result.errors + result.warnings
    context.command_result = result

    # For /rfc-generate commands, also set context.generated_rfc
    if command.startswith('/rfc-generate'):
        if result.files_created:
            # Find the RFC file (not rfc-map.json)
            rfc_files = [f for f in result.files_created if f.endswith('.md')]
            if rfc_files:
                context.generated_rfc = rfc_files[0]
        else:
            # Fallback: infer from command
            docs_dir = os.path.join(str(context.test_repo), 'docs', 'generated')
            if '--output' in command:
                output_file = command.split('--output')[1].strip().split()[0]
            else:
                output_file = 'draft-generated-latest.md'
            context.generated_rfc = os.path.join(docs_dir, output_file)


@given('I modify the code that maps to section "{section}"')
def step_modify_code_for_section(context: Context, section: str):
    """Simulate modifying code that affects specific RFC section"""
    step_modify_method_signature(context, 'src/calculator.py', 'Calculator.add')
    context.affected_section = section


@when('I change the signature to "{new_signature}"')
def step_change_signature_to(context: Context, new_signature: str):
    """Document the new signature"""
    context.new_signature = new_signature


@given('I modify "{file_path}"')
def step_modify_file_given(context: Context, file_path: str):
    """Simulate modifying a file (generic given)"""
    full_path = os.path.join(str(context.test_repo), file_path)
    if os.path.exists(full_path):
        with open(full_path, 'a') as f:
            f.write('\n# Modified content\n')
    context.code_changed = True
    context.modified_file = file_path


@when('I modify "{file_path}"')
def step_modify_file_when(context: Context, file_path: str):
    """Simulate modifying a file (when variant)"""
    step_modify_file_given(context, file_path)


@given('I modify "{file_path}" function "{function_name}" (section {section})')
def step_modify_function_with_section(context: Context, file_path: str, function_name: str, section: str):
    """Simulate modifying a function with section tracking"""
    full_path = os.path.join(str(context.test_repo), file_path)
    # Create utils.py if needed
    if not os.path.exists(full_path):
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, 'w') as f:
            f.write(f'''def {function_name}(value):
    """Validate input value"""
    if not isinstance(value, (int, float)):
        raise TypeError("Input must be numeric")
    return True
''')
    else:
        with open(full_path, 'a') as f:
            f.write(f'\n# Modified {function_name}\n')

    context.code_changed = True
    context.affected_section = section


@given('I modify code that generates content for lines {start:d}-{end:d}')
def step_modify_code_lines_range(context: Context, start: int, end: int):
    """Simulate modifying code that affects specific line range"""
    context.modified_lines = (start, end)
    context.code_changed = True


@given('I modify code affecting sections "{sections}"')
def step_modify_code_affecting_sections(context: Context, sections: str):
    """Simulate modifying code affecting multiple sections"""
    section_list = [s.strip().strip('"') for s in sections.split('and')]
    context.affected_sections = section_list
    context.code_changed = True
    # Modify source files
    for section in section_list:
        if '3.1' in section:
            step_modify_method_signature(context, 'src/calculator.py', 'Calculator.add')


@when('I modify code in section "{section}" only')
def step_modify_code_in_section_only(context: Context, section: str):
    """Simulate modifying code in specific section"""
    context.affected_section = section
    context.modified_section_filter = [section]
    step_modify_method_signature(context, 'src/calculator.py', 'Calculator.add')


@when('I modify "{symbol}" (line number changes to {line:d})')
def step_modify_symbol_line_change(context: Context, symbol: str, line: int):
    """Simulate modifying a symbol with line number change"""
    context.modified_symbol = symbol
    context.new_line_number = line
    context.code_changed = True
    # Simulate file modification that shifts line numbers
    full_path = os.path.join(str(context.test_repo), 'src/calculator.py')
    if os.path.exists(full_path):
        with open(full_path, 'r') as f:
            lines = f.readlines()
        # Add blank lines to shift line numbers
        lines.insert(44, '\n')
        lines.insert(44, '\n')
        with open(full_path, 'w') as f:
            f.writelines(lines)


@given('the frontmatter contains "{field}: {value}"')
def step_frontmatter_contains_field(context: Context, field: str, value: str):
    """Add field to frontmatter"""
    # Read existing RFC
    with open(context.existing_rfc_path, 'r') as f:
        content = f.read()

    # Add field after docname
    if field not in content:
        updated = content.replace(
            'category: info',
            f'category: info\n{field}: {value}'
        )
        with open(context.existing_rfc_path, 'w') as f:
            f.write(updated)


@given('an existing RFC documenting "{signature}"')
def step_existing_rfc_documenting_signature(context: Context, signature: str):
    """Set up RFC documenting specific signature"""
    step_existing_rfc_generated(context)
    context.documented_signature = signature


@when('the formatter agent is spawned with section_filter {section_list}')
def step_formatter_spawned_with_filter(context: Context, section_list: str):
    """Simulate formatter being spawned with section filter"""
    import ast
    context.section_filter = ast.literal_eval(section_list)


@when('the formatter agent fails during execution')
def step_formatter_fails(context: Context):
    """Simulate formatter agent failure"""
    context.agent_failed = True
    context.command_exit_code = 1
